// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmegaExplorer.Server.Services.Databases;

#nullable disable

namespace OmegaExplorer.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251001155512_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ActionInBattleSpaceship", b =>
                {
                    b.Property<Guid>("ActionsAsTargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionsAsTargetId", "TargetsId");

                    b.HasIndex("TargetsId");

                    b.ToTable("ActionInBattleSpaceship");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services.Users.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTechnologyResearchIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastConnection")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("FactionLosers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("FactionWinners")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PlayerLoserIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PlayerWinnerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BattleId")
                        .IsUnique();

                    b.ToTable("BattleResults");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleRewardResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BattleResultId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndexResource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BattleResultId");

                    b.ToTable("BattleResultRewards");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.ActionInBattle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorSpaceshipId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cycle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorSpaceshipId");

                    b.HasIndex("BattleId");

                    b.ToTable("BattleActions");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Buildings.Models.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Cycles.Models.Entities.CycleState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CycleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CycleStates");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Events.Models.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Galaxies.Models.Entities.Galaxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UniverseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId");

                    b.ToTable("Galaxies");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.GameResources.Models.Entities.GameResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderableId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRaw")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetSpaceshipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderableId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TargetLocationId");

                    b.HasIndex("TargetSpaceshipId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Orderable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orderables");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Personalities.Models.Classes.ManagedByPersonality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PersonalityId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ManagedByPersonalities");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Personalities.Models.Entities.Personality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManagedByPersonalityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PortraitIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByPersonalityId")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Personalities");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Quests.Models.Entities.QuestProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestObjectiveProgresses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuestProgresses");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Scenarios.Models.Entities.UserScenarioProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Choices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScenarioProgresses");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipBlueprint.Models.Entities.BlueprintSpaceship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("BlueprintSpaceships");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipBlueprint.Models.Entities.BlueprintSpaceshipModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlueprintSpaceshipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintSpaceshipId");

                    b.ToTable("BlueprintSpaceshipModules");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipModule.Models.Entities.SpaceshipModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndexBrand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpaceshipId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("SpaceshipModules");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Classes.SpatialLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GalaxyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StarClusterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UniverseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GalaxyId");

                    b.HasIndex("StarClusterId");

                    b.HasIndex("UniverseId");

                    b.ToTable("SpatialLocations");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Technologies.Models.Entities.TechnologyKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Knowledge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TechnologyIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TechnologyKnowledges");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Universes.Models.Entities.Universe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CycleWhenRemove")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeletion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEdition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Universes");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Orderable");

                    b.Property<Guid>("SpatialLocationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeedInGalaxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedInStarCluster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedInUniverse")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SpatialLocationId");

                    b.ToTable("SpatialObjects", (string)null);
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject");

                    b.Property<long>("EndAtCycle")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartAtCycle")
                        .HasColumnType("INTEGER");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject");

                    b.Property<bool>("AutoBattle")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BattleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DestroyedQuantityDamageToRepair")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawBlueprint")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("BattleId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarClusters.Models.Entities.StarCluster", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject");

                    b.ToTable("StarClusters");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("OwnerId");

                    b.ToTable("StarSystems");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Instability", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem");

                    b.Property<int>("TypeInstability")
                        .HasColumnType("INTEGER");

                    b.ToTable("Instabilities");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Planet", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Star", b =>
                {
                    b.HasBaseType("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem");

                    b.ToTable("Stars");
                });

            modelBuilder.Entity("ActionInBattleSpaceship", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.ActionInBattle", null)
                        .WithMany()
                        .HasForeignKey("ActionsAsTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", null)
                        .WithMany()
                        .HasForeignKey("TargetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services.Users.Models.Entities.User", b =>
                {
                    b.OwnsOne("OmegaExplorer.Server.Services._Game.Origins.Models.Entities.Origin", "Origin", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("IndexHistory")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("IndexSpecies")
                                .HasColumnType("INTEGER");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleResult", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", "Battle")
                        .WithOne("Result")
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleResult", "BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battle");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleRewardResult", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleResult", null)
                        .WithMany("Rewards")
                        .HasForeignKey("BattleResultId");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.ActionInBattle", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", "Actor")
                        .WithMany("ActionsAsActor")
                        .HasForeignKey("ActorSpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", "Battle")
                        .WithMany("Actions")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.ActionInBattleResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("ActionInBattleId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Absorb")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Bounce")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Critical")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DiceActor")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("DiceTarget")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Dodge")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("ModuleIds")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ActionInBattleId");

                            b1.ToTable("BattleActions");

                            b1.WithOwner()
                                .HasForeignKey("ActionInBattleId");
                        });

                    b.Navigation("Actor");

                    b.Navigation("Battle");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Buildings.Models.Entities.Building", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", "System")
                        .WithMany("Buildings")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Events.Models.Entities.Event", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Galaxies.Models.Entities.Galaxy", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Universes.Models.Entities.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.GameResources.Models.Entities.GameResource", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "User")
                        .WithMany("GameResources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Order", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Orderable", "Orderable")
                        .WithMany("Orders")
                        .HasForeignKey("OrderableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "Owner")
                        .WithMany("Orders")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Classes.SpatialLocation", "TargetLocation")
                        .WithMany()
                        .HasForeignKey("TargetLocationId");

                    b.HasOne("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", "TargetSpaceship")
                        .WithMany()
                        .HasForeignKey("TargetSpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Orderable");

                    b.Navigation("Owner");

                    b.Navigation("TargetLocation");

                    b.Navigation("TargetSpaceship");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Personalities.Models.Entities.Personality", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Personalities.Models.Classes.ManagedByPersonality", "ManagedByPersonality")
                        .WithOne("Personality")
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.Personalities.Models.Entities.Personality", "ManagedByPersonalityId");

                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "Owner")
                        .WithMany("Personalities")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagedByPersonality");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Quests.Models.Entities.QuestProgress", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "User")
                        .WithMany("Quests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Scenarios.Models.Entities.UserScenarioProgress", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "User")
                        .WithMany("ScenarioProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipBlueprint.Models.Entities.BlueprintSpaceship", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "Owner")
                        .WithMany("BlueprintSpaceships")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipBlueprint.Models.Entities.BlueprintSpaceshipModule", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipBlueprint.Models.Entities.BlueprintSpaceship", "BlueprintSpaceship")
                        .WithMany("Modules")
                        .HasForeignKey("BlueprintSpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlueprintSpaceship");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipModule.Models.Entities.SpaceshipModule", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", "Spaceship")
                        .WithMany("Modules")
                        .HasForeignKey("SpaceshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spaceship");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Classes.SpatialLocation", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Galaxies.Models.Entities.Galaxy", "Galaxy")
                        .WithMany()
                        .HasForeignKey("GalaxyId");

                    b.HasOne("OmegaExplorer.Server.Services._Game.StarClusters.Models.Entities.StarCluster", "StarCluster")
                        .WithMany()
                        .HasForeignKey("StarClusterId");

                    b.HasOne("OmegaExplorer.Server.Services._Game.Universes.Models.Entities.Universe", "Universe")
                        .WithMany()
                        .HasForeignKey("UniverseId");

                    b.OwnsOne("OmegaExplorer.Server.Services._Game._core.Models.Classes.Vector2", "Position", b1 =>
                        {
                            b1.Property<Guid>("SpatialLocationId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SpatialLocationId");

                            b1.ToTable("SpatialLocations");

                            b1.WithOwner()
                                .HasForeignKey("SpatialLocationId");
                        });

                    b.Navigation("Galaxy");

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("StarCluster");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Technologies.Models.Entities.TechnologyKnowledge", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "User")
                        .WithMany("Researches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Orderable", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Classes.SpatialLocation", "SpatialLocation")
                        .WithMany()
                        .HasForeignKey("SpatialLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SpatialLocation");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", "Battle")
                        .WithMany("Spaceships")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "Owner")
                        .WithMany("Spaceships")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Battle");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarClusters.Models.Entities.StarCluster", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.StarClusters.Models.Entities.StarCluster", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.SpatialObjects.Models.Entities.SpatialObject", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmegaExplorer.Server.Services.Users.Models.Entities.User", "Owner")
                        .WithMany("Planets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Instability", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Instability", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Planet", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Planet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Star", b =>
                {
                    b.HasOne("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", null)
                        .WithOne()
                        .HasForeignKey("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.Star", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services.Users.Models.Entities.User", b =>
                {
                    b.Navigation("BlueprintSpaceships");

                    b.Navigation("Events");

                    b.Navigation("GameResources");

                    b.Navigation("Orders");

                    b.Navigation("Personalities");

                    b.Navigation("Planets");

                    b.Navigation("Quests");

                    b.Navigation("Researches");

                    b.Navigation("ScenarioProgresses");

                    b.Navigation("Spaceships");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Classes.BattleResult", b =>
                {
                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Orders.Models.Entities.Orderable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Personalities.Models.Classes.ManagedByPersonality", b =>
                {
                    b.Navigation("Personality");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Services.SpaceshipBlueprint.Models.Entities.BlueprintSpaceship", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Battles.Models.Entities.Battle", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Result");

                    b.Navigation("Spaceships");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.Spaceships.Models.Entities.Spaceship", b =>
                {
                    b.Navigation("ActionsAsActor");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("OmegaExplorer.Server.Services._Game.StarSystems.Models.Entities.StarSystem", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
