using OmegaExplorer.Server.Services._Game._core.Models.Enums;
using OmegaExplorer.Server.Services._Game.GameResources.Models.Interfaces;
using OmegaExplorer.Server.Services._Game.Technologies.Models.Enums;

namespace OmegaExplorer.Server.Services._Game.GameResources.Data;

public class DynamicItemGameResource_2_Electricity : IDynamicItemGameResource
{
    public const int INDEX = 2;

    public int Index
    {
        get => INDEX;
        set => throw new NotImplementedException();
    }

    public string Name { get; set; } = "Electricity";

    public string? Description { get; set; } =
        "Electricity is a resource that is used to power starship systems and equipment. It is generated by power plants and can be stored in batteries for later use.";

    public EnumDataKnowledge Knowledge { get; set; } = EnumDataKnowledge.Unlocked;

    public EnumRarity Rarity { get; set; } = EnumRarity.Common;
}